---
- name: Installing docker (apt)
  become: yes
  apt:
    name:
      - docker.io
    state: present
    update_cache: yes

- name: Adding docker daemon.json
  become: yes
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0640
  notify: restart docker service

- name: Force restart docker if needed
  meta: flush_handlers

- name: Creating new docker directory
  become: yes
  file:
    path: "{{ docker_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0750
  notify: remove old docker directory

- name: Force create new docker directory
  meta: flush_handlers
