- name: Install filebeat (apt)
  become: yes
  apt:
    name:
      - filebeat={{ es_version }}
    state: present
    update_cache: yes
  notify: setup filebeat dashboards
  tags:
    - packages
    - beats-setup

- name: Copy filebeat.yml config file to the host
  become: yes
  template:
    src: etc/filebeat/filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: u=rwX,g=rX,o=-rwx
  notify: restart filebeat
  tags:
    - config

- name: Copy RedELK CA file to the hosts
  become: yes
  copy:
    src: certificates/redelk/redelkCA.crt
    dest: /etc/filebeat/redelkCA.crt
    owner: root
    group: root
    mode: u=rwX,g=rX,o=-rwx
  notify: restart filebeat
  tags:
    - pki

- name: Recursively setting permissions of /etc/filebeat folder
  become: yes
  file:
    path: /etc/filebeat
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: u=rwX,g=rX,o=-rwx
  tags:
    - config
    - pki

- name: Flush handlers
  meta: flush_handlers
