---
- name: Copy /etc/logstash/* configuration file to the hosts
  become: yes
  template:
    src: "{{ item }}"
    dest: "/etc/logstash/{{ item | basename | regex_replace('.j2','') }}"
    owner: root
    group: logstash
    mode: u=rwX,g=rX,o=-rwx
  with_fileglob:
    - ../templates/etc/logstash/*
  notify: restart logstash

- name: Copy /etc/logstash/conf.d/* configuration files to the hosts
  become: yes
  template:
    src: "{{ item }}"
    dest: "/etc/logstash/conf.d/{{ item | basename | regex_replace('.j2','') }}"
    owner: root
    group: logstash
    mode: u=rwX,g=rX,o=-rwx
  with_fileglob:
    - ../templates/etc/logstash/conf.d/*
  notify: restart logstash

- name: Copy RedELK certs to /etc/logstash folder
  become: yes
  copy:
    src: "{{ redelk_cert_path }}/{{ item }}"
    dest: "/etc/logstash/{{ item }}"
    owner: root
    group: logstash
    mode: u=rwX,g=rX,o=-rwx
  with_items:
    - "{{ ansible_hostname }}.crt"
    - "{{ ansible_hostname }}.key"
    - redelkCA.crt
  notify:
    - convert logstash key to pkcs8
    - restart logstash

- name: Copy logstash ruby scripts file to the hosts
  become: yes
  copy:
    src: etc/logstash/ruby-scripts
    dest: /etc/logstash/
    owner: root
    group: logstash
    mode: u=rwX,g=rX,o=-rwx

- name: Recursively setting permissions of /etc/logstash folder
  become: yes
  file:
    path: /etc/logstash
    state: directory
    recurse: yes
    owner: root
    group: logstash
    mode: u=rwX,g=rX,o=-rwx

- name: Flush handlers
  meta: flush_handlers
