---
# RedELK server installation tasks

# Calculate ES & Jupyter memory
- import_tasks: memory.yml
  tags:
    - elasticsearch
    - memory
    - redelk-setup

# Setup needed users and SSH access
- import_tasks: ssh.yml
  tags:
    - ssh

# Installed required packages
- import_tasks: packages.yml
  tags:
    - packages

# Apply docker fixes
- import_tasks: docker.yml
  tags:
    - docker

# Setup RedELK
- import_tasks: redelk-setup.yml
  tags:
    - redelk-setup

# Setup SSH reverse tunnel to client if redelk_client_connection_mode == 'reverse'
- import_tasks: ssh-tunnel.yml
  tags:
    - ssh-tunnel
  when: redelk_client_connection_mode == 'reverse'
