---
# RedELK server installation tasks

# Calculate ES & Jupyter memory
- import_tasks: memory.yml
  tags:
    - elasticsearch
    - memory

# Setup needed users and SSH access
- import_tasks: ssh.yml
  tags:
    - ssh

# Installed required packages
- import_tasks: packages.yml
  tags:
    - packages

# Full install - Jupyter + Neo4J/BloodHound
- import_tasks: full.yml
  tags:
    - redelk_install_full
  when: redelk_limited_install|bool == False

# Generate certificates
- import_tasks: pki-elastic.yml
  tags:
    - pki

# Setup ElasticSearch
- import_tasks: elasticsearch.yml
  tags:
    - elasticsearch

# Setup Logstash
- import_tasks: logstash.yml
  tags:
    - logstash

# Setup Kibana
- import_tasks: kibana.yml
  tags:
    - kibana

# Setup Nginx
- import_tasks: nginx.yml
  tags:
    - nginx

# Setup filebeat
- import_tasks: filebeat.yml
  tags:
    - filebeat

# Setup RedELK
- import_tasks: redelk-setup.yml
  tags:
    - redelk-setup
- import_tasks: redelk-config.yml
  tags:
    - redelk-config

# Setup CRON tasks
- import_tasks: cron.yml
  tags:
    - cron

# Setup SSH reverse tunnel to client if redelk_client_connection_mode == 'reverse'
- import_tasks: ssh-tunnel.yml
  tags:
    - ssh-tunnel
  when: redelk_client_connection_mode == 'reverse'
