- name: Installing packages requirements (apt)
  become: yes
  apt:
    name:
      - docker.io
      - docker-compose
      - unzip
      - apt-transport-https
      - python3-netaddr
      - python3-docker
      - python3-passlib
      - python-passlib
      - python-docker
      - python-netaddr
    state: present
    update_cache: yes
