- name: Installing packages requirements (apt)
  become: yes
  apt:
    name:
      - docker.io
      - docker-compose
      - unzip
      - apt-transport-https
    state: present
    update_cache: yes

- name: Install python packages requirements (pip)
  pip:
    name: "{{ item }}"
  with_items:
    - docker-compose
    - docker
    - passlib
    - netaddr
