---
# 1. clone RedELK repo
# 2. prepare steps from init script
# 3. prepare stesp from elkserver setup
# 4. deploy using docker-compose
- name: Checkout RedELK git repo (localhost)
  git:
    repo: 'https://github.com/{{ redelk_repo }}/RedELK.git'
    dest: "{{ redelk_repo_path }}"
    version: "{{ redelk_version }}"
  ignore_errors: yes
  delegate_to: localhost

- name: Creating RedELK working directory
  become: yes
  file:
    path: "{{ optsec_dir }}/{{ redelk_user }}/mounts/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - certs
    - jupyter-workbooks
    - logstash-config
    - nginx-config
    - redelk-config/etc/cron.d
    - redelk-config/etc/redelk
    - redelk-logs
    - redelk-ssh
    - redelk-www

# jupyter
- name: Copying Jupyter workbooks from RedELK repository
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ optsec_dir }}/{{ redelk_user }}/mounts/jupyter-workbooks/{{ item | basename }}"
  with_fileglob:
    - "{{ redelk_repo_path }}/elkserver/mounts/jupyter-workbooks/*"

# logstash
- name: Copying logstash config files from RedELK repository
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ optsec_dir }}/{{ redelk_user }}/mounts/logstash-config/{{ item | basename }}"
  with_fileglob:
    - "{{ redelk_repo_path }}/elkserver/docker/redelk-logstash/redelkinstalldata/redelk-main/conf.d/*"

# nginx
- name: Copying nginx config file
  become: yes
  template:
    src: nginx-config/default.conf.j2
    dest: "{{ optsec_dir }}/{{ redelk_user }}/mounts/nginx-config/default.conf"

- name: Create Nginx htpasswd file
  become: yes
  htpasswd:
    path: "{{ optsec_dir }}/{{ redelk_user }}/mounts/nginx-config/htpasswd.users"
    name: "{{ es_redelk_user }}"
    password: "{{ es_redelk_password }}"
    owner: root
    group: www-data
    mode: 0640

# cron
- name: Copying RedELK cron file
  become: yes
  template:
    src: redelk-config/etc/cron.d/redelk.j2
    dest: "{{ optsec_dir }}/{{ redelk_user }}/mounts/redelk-config/etc/cron.d/redelk"

# RedELK config files
- name: Copying RedELK config files
  become: yes
  template:
    src: "{{ item }}"
    dest: "{{ optsec_dir }}/{{ redelk_user }}/mounts/redelk-config/etc/redelk/{{ item | basename | regex_replace('.j2','') }}"
  with_fileglob:
    - ../templates/redelk-config/etc/redelk/*.j2

# Docker-compose
- name: Copying docker-compose from RedELK repository
  become: yes
  copy:
    src: "{{ redelk_repo_path }}/elkserver/redelk-{{ redelk_install_type }}.yml"
    dest: "{{ optsec_dir }}/{{ redelk_user }}/redelk-{{ redelk_install_type }}.yml"
- name: Generating docker-compose .env file
  become: yes
  template:
    src: docker-env.j2
    dest: "{{ optsec_dir }}/{{ redelk_user }}/.env"
    mode: 0640

- name: Run `docker-compose up` again
  become: yes
  community.general.docker_compose:
    project_src: "{{ optsec_dir }}/{{ redelk_user }}"
    files: "redelk-{{ redelk_install_type }}.yml"
    build: no
  register: output
