---
- name: restart autossh services
  become: yes
  systemd:
    name: "autossh-tunnel-{{ item }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  with_items:
    - "{{ hostvars.values()|list|json_query(\"[?type=='redirector'].ansible_hostname\") }}"
    - "{{ hostvars.values()|list|json_query(\"[?type=='c2'].ansible_hostname\") }}"
  tags:
    - ssh
    - service

- name: update-ca-certificates
  become: yes
  command: "update-ca-certificates"
