---
- name: restart autossh services
  become: yes
  systemd:
    name: "autossh-tunnel-{{ item }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  with_items:
    - "{{ hostvars.values()|list|json_query(\"[?type=='redirector'].ansible_hostname\") }}"
    - "{{ hostvars.values()|list|json_query(\"[?type=='c2'].ansible_hostname\") }}"
  tags:
    - ssh
    - service

- name: fetch redelk certificates
  become: yes
  synchronize:
    src: "{{ optsec_dir }}/{{ redelk_user }}/mounts/certs/"
    dest: "{{ redelk_cert_path }}/"
    mode: pull
    use_ssh_args: yes

- name: update-ca-certificates
  become: yes
  command: "update-ca-certificates"
